[package]
name = "test-programs"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
futures-lite.workspace = true
serde_json.workspace = true
wstd.workspace = true
wasi.workspace = true
